# Generated by Django 5.2.4 on 2025-08-01 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the component.", max_length=200
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The main content of the component, can be HTML."
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="A unique identifier for this component, used to load it in the frontend.",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The display name of the menu item.", max_length=50
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="The URL this menu item points to.", max_length=200
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="The order in which the item appears in the menu.",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="The parent menu item, if this is a sub-menu.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="api.menu",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
